### ISSUE TITLE
ReportsByCountries not available for India

### ISSUE THREAD

**Issue by raghav4** [ChrisMichaelPerezSantiago/covid19#1]
`ReportsByCountries` is not available for India.

**Comment by ChrisMichaelPerezSantiago** [comment]
Hi @raghav4 

_Currently the worldometers website has not published information regarding **active cases**, **closed cases** in India._

_sorry for the inconvenience!_

**Comment by raghav4** [comment]
@ChrisMichaelPerezSantiago okay! 👍
