### ISSUE TITLE
All Report Not Working

### ISSUE THREAD

**Issue by varundeva** [ChrisMichaelPerezSantiago/covid19#15]
Plz Look into it
all Reports Api is Down
!
Also Tell HOw to Run it Locally

**Comment by ChrisMichaelPerezSantiago** [comment]
Hi @varundeva 

Problem solved #11

**Comment by ChrisMichaelPerezSantiago** [comment]
_If you mean to correct the server, you should go to the `folder server`._

_Then write the terminal_

```shell
npm install
```

_That will install all the necessary packages to run the server locally._
_After all the packages are installed, you will stay in the same folder `server`._

_There you will write in the terminal_

```shell
npm run dev
```
_Now he would show in the terminal a local url to verify the API._

**Comment by varundeva** [comment]
Hey. Showing Some Error 

![Screenshot from 2020-03-30 21-41-31](https://user-images.githubusercontent.com/25100605/77935590-433ba300-72cf-11ea-8ec6-691d2f6d27fd.png)

**Comment by ChrisMichaelPerezSantiago** [comment]
_From what I see, there is not much information to help you._
_What steps did you do first?_

**Comment by varundeva** [comment]
I Directly Uploaded to Heroku. There it worked. In local not working. But
no problem i use from heroku.
Thanks
