### ISSUE TITLE
You would be a racist to call the virus the "Wuhan Virus" or "Wuhan Corona Virus".

### ISSUE THREAD

**Issue by silver-xu** [ChrisMichaelPerezSantiago/covid19#17]
It has been noticed that you have called the COVID-19 virus the "Wuhan Virus" across your Readme section.

This has been greatly discouraged to use a location name to name a human transferable disease. Please see link here [https://www.who.int/mediacentre/news/notes/2015/naming-new-diseases/en/](url). 

You have developed a very promising API here and I am sure your intention was good, but it would hurt people from China (especially from Wuhan) by calling this virus by this insulting name. None of the Chinese would want the disease to happen, ever! Could you imagine if we call the H1N1 the "American Virus"?

I really wish you could turn your mind around and update all your references in the repo from "Wuhan Virus" or "Wuhan Coronavirus" to its real name "COVID-19". Our enemy is not the Chinese or Wuhanese, our enemy is the virus.

Please address this issue at your earliest convenience.

**Comment by ChrisMichaelPerezSantiago** [comment]
_Good morning @silver-xu ,_

_I understand your posture_
_By providing information my intention was not to cause any problems, much less racism._
