### ISSUE TITLE
Get All Reports Endpoint Not working

### ISSUE THREAD

**Issue by SamChathu** [ChrisMichaelPerezSantiago/covid19#19]
502 - bad gateway 

An error occurred with this application.

NO_STATUS_CODE_FROM_FUNCTION

**Comment by surajmandalcell** [comment]
+1

**Comment by NathanielGiron** [comment]
Access to fetch at 'https://covid19-server.chrismichael.now.sh/api/v1/AllReports' from origin '<my-website-url>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by coenraadhuman** [comment]
Experiencing the same issues.

**Comment by ChrisMichaelPerezSantiago** [comment]
_Good morning,_

_Problem solved,_

_To see the report go to the following_ [url](https://github.com/ChrisMichaelPerezSantiago/covid19/issues/6#issuecomment-607878576)
