### ISSUE TITLE
can you add Pakistan to country list please . 

### ISSUE THREAD

**Issue by agustin21453** [ChrisMichaelPerezSantiago/covid19#2]

**Comment by ChrisMichaelPerezSantiago** [comment]
_Hi @agustin21453 ,_

_Sorry for the delay_

_Yes, you can find information about Pakistan using the API._

_the **function** `getReports()`_ 
or by accessing ...
_the **URL** https://covid19-server.chrismichael.now.sh/api/v1/AllReports_

_For now there is no information about this country if you use the_ 
**URL**:  _/api/v1/ReportsByCountries/:country,_

**Comment by ChrisMichaelPerezSantiago** [comment]
Hi @agustin21453 ,

_You can now access partial information about **pakistan**_
**URL**: /api/v1/ReportsByCountries/:country,

_In any case the table of the countries was updated, it already has almost all the countries._

From this [URL](https://github.com/ChrisMichaelPerezSantiago/covid19/issues/6#issue-587800563) you can verify the list.
