### ISSUE TITLE
Strings s/b surrounded by double quotes

### ISSUE THREAD

**Issue by w8HAQRHkTx7r** [ChrisMichaelPerezSantiago/covid19#23]
According to the JSON standard, [https://tools.ietf.org/html/rfc7159#section-7](https://tools.ietf.org/html/rfc7159#section-7), keys and values should be surrounded by "  instead of the ' which is being output in this API.  The examples in the README show both being used, but I'm only seeing the single quote.  Can that be changed?

**Comment by ChrisMichaelPerezSantiago** [comment]
Hi @w8HAQRHkTx7r ,

_Quite curious._

_From what I've tried, all endpoin keys are covered with ""._

Regarding the values, some are of type string and others are of type number.

**_I must understand that yes, the object is correctly built and follows the standards of a JSON._**

If you want, you can provide me the output of the endpoint URL or the function if you are using the library.

**Comment by w8HAQRHkTx7r** [comment]
How curious!  After additional testing on other platforms, it now appears that the json parser I use in Python on Raspberry Pi is the culprit.
