### ISSUE TITLE
Data for 4/9/20 in JohnsHopkinsDataDailyReport is stale

### ISSUE THREAD

**Issue by w8HAQRHkTx7r** [ChrisMichaelPerezSantiago/covid19#24]
Today's [https://covid19-server.chrismichael.now.sh/api/v1/JohnsHopkinsDataDailyReport](https://covid19-server.chrismichael.now.sh/api/v1/JohnsHopkinsDataDailyReport ) query, filtered for the state of Illinois (the only one I've tested) shows no change in the data from the previous day and differs from the numbers displayed on the Johns Hopkins web site https://coronavirus.jhu.edu/map.html and the IDPH site http://www.dph.illinois.gov/topics-services/diseases-and-conditions/diseases-a-z-list/coronavirus as of 4/10/20 @ 7am CST.
Here's a sample of this morning's query:
`"Cook, Illinois, US", 10520, 2020-04-09 23:02:37`
`"DuPage, Illinois, US", 875, 2020-04-09 23:02:37`
`"Kendall, Illinois, US", 79, 2020-04-09 23:02:37`
`"Will, Illinois, US", 914, 2020-04-09 23:02:37`

This are the values reported elsewhere.
`11415`
`  943`
`    86`
` 1010`

**Comment by Nerko69** [comment]
Thanks for the update.

**Comment by w8HAQRHkTx7r** [comment]
Data appears to be in-sync as expected this morning.  

There was an odd looking datapoint:

`"Utah","US",2020-04-10 22:54:07,"unassigned, Utah, US",0,4,0,0`

It's the only datapoint that includes "unassigned" in the combined key.  I would have expected a county name or "Utah".  I that datapoint appeared yesterday.  I'll keep this issue open for a day or two more as I keep an eye on things.

**Comment by w8HAQRHkTx7r** [comment]
There continues to be a little dirt in the data.  Just be careful.
