### ISSUE TITLE
Wrong data for FatalityRateBySex

### ISSUE THREAD

**Issue by blazerzar** [ChrisMichaelPerezSantiago/covid19#25]
As I checked the API docs, the call FatalityRateBySex should return JSON with keys: 
Sex, DeathRateConfirmedCases, DeathRateAllCases,
which it does, but in reality they really look more like some other data for FatalityRateByAge, only that the numbers are different.
I believe Worldometer has added another table onto the website and now the this call is not working correctly anymore.

Could this be resolved?

**Comment by ChrisMichaelPerezSantiago** [comment]
Hello blazerzar ,

During the weekend (Saturday / Sunday) I will fix the problem.

Thank you for letting me know.

**Comment by ChrisMichaelPerezSantiago** [comment]
Apparently I also have to correct the following endpoints, 

```json
  "FatalityRateByAge": "/api/v1/FatalityRateByAge",
  "FatalityRateBySex": "/api/v1/FatalityRateBySex",
  "FatalityRateByComorbidities": "/api/v1/FatalityRateByComorbidities",
```

this because more tables have been added in the section and the tables I was pointing to no longer refer to the correct data.

**Comment by ChrisMichaelPerezSantiago** [comment]
Hi @blazerzar ,

Sorry for the delay!

Fatality Rate By [age, sex, Comorbidities] return object fixed.
