### ISSUE TITLE
COVID19 API - It will no longer be active!

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [ChrisMichaelPerezSantiago/covid19#29]
_Good Morning,_

_To notify you that unfortunately the covid19 API will no longer be available, as I have exceeded the request per second limit that the vercel platform allows._

_This is the report for the period - JULY 5, 2020 - AUGUST 4, 2020_

_1 / Domains_
_648 GB / Bandwidth_

_I am very sorry about the situation, as I am aware that there are many people using this API to inform society about COVID19 case numbers._

_But even so I am very grateful for the support I received from everyone !!_

But you still have the option to use the [npm package]( https://www.npmjs.com/package/covid19-api), if you want.

**Comment by ChrisMichaelPerezSantiago** [comment]
_Report for the period - JULY 5, 2020 - AUGUST 4, 2020_

![Capture](https://user-images.githubusercontent.com/21962584/89305960-44922900-d63d-11ea-9eb2-53acbdc06f10.JPG)

**Comment by chrismaurer** [comment]
Oh That's too bad. Thanks for creating this API, though. I used it once per day for the past several months and found it very useful.

**Comment by ChrisMichaelPerezSantiago** [comment]
Please visit the following reference #30
