### ISSUE TITLE
New alternative to the COVID19 API

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [ChrisMichaelPerezSantiago/covid19#30]
Good to everyone,

To notify you that my partner [Orgest Shehaj](https://github.com/emulk/), has offered to help me provide the latest COVID19 data on a temporary basis with its own server, which I really appreciate.

We will both be working on a full API, this will be an improved version more focused for developers. Therefore, we ask for your patience at this time as we begin with the development of the official API.

Meanwhile, I leave you the repository where you can find the [URLs](https://github.com/emulk/covid19API?fbclid=IwAR2Q9o7nE1RhNxkmVp8A8sCRPu8eUmW5hUigkCrh0EAchQBAvRD8hxHC_4s) of the data "temporarily".

If you have any questions about the data offered by my partner, you can contact him at

- [x] https://github.com/emulk
- [x]  info@ncovid19.it

**Comment by samthomson** [comment]
Thanks for the API while it lasted and I look/hope forward to a next edition.

Note to other devs, the temporary API routes return quite different data than before (eg US states).
