### ISSUE TITLE
Can please add Pakistan to country list as well

### ISSUE THREAD

**Issue by Lutif** [ChrisMichaelPerezSantiago/covid19#4]
First of all, thank you for such a great package. Can you make Pakistan's data available as well. It's numbers also increasing at an alarming rate and I am working on an app to provide information and awareness about for its people.

**Comment by CopyMist** [comment]
I wonder, does the author of this repo want a separate issue for each country that's not supported right now? Why not make a good solution with all the data provided on Worldometers?

But yeah.. design and emojis come first, who needs correct data for an API?

**Comment by ChrisMichaelPerezSantiago** [comment]
_Hi @CopyMist_

Good morning,
_Sorry for the delay._

_First of all,_

_I understand that this API is being used considerably by many people and I understand the responsibility of maintaining and bringing valid information to everyone._

_But I have to say, I am doing this alone and sometimes I don't have enough time to spend more hours on the API._


_What you are proposing to me about using Worldometers, I am working with that website and other pages that also provide valuable information._

_What you are proposing to me about creating an issue about the countries that I do not have information, I can do today, if time permits._

**Comment by ChrisMichaelPerezSantiago** [comment]
Hi @Lutif 

_See this #2_
