### ISSUE TITLE
ReportsByCountries

### ISSUE THREAD

**Issue by Pomdre** [ChrisMichaelPerezSantiago/covid19#5]
Add NewCases, NewDeaths and Tot Cases/1M pop to ReportsByCountries.

**Comment by ChrisMichaelPerezSantiago** [comment]
_Hi @Pomdre  ,_

_That type of information is not available, if you enter the official website https://www.worldometers.info/coronavirus/country/china/_

_You will see that **worldometers** has not provided the information you are requesting._
