### ISSUE TITLE
Can't seem to get :country to work consistently

### ISSUE THREAD

**Issue by hxhieu** [ChrisMichaelPerezSantiago/covid19#7]
Hi,

First of all thanks for the API, it looks amazing but I having problem with this particular API `/api/v1/ReportsByCountries/:country`

It works if I do `/api/v1/ReportsByCountries/China`
But it crashes if I do `/api/v1/ReportsByCountries/Japan` or `/api/v1/ReportsByCountries/New%20Zealand`

I am not sure what "country" strings should we use?

Cheers,
Hugh

**Comment by ChrisMichaelPerezSantiago** [comment]
_Hi @hxhieu_ 

_You should go to the next issue #6 ._

_In the table you will find the parameters that are valid for now._
